export enum CampaignType {
  LIVESTREAMS = "livestreams",
  CONTENT_REWARDS = "content-rewards",
  APP_STORE = "app-store",
  TRADING = "trading",
  SPORTS_PICKS = "sports-picks",
  RESELLING = "reselling",
  ECOMMERCE = "ecommerce",
  REAL_ESTATE = "real-estate",
  PERSONAL_DEVELOPMENT = "personal-development",
  PERSONAL_FINANCE = "personal-finance",
  CAREERS = "careers",
  TRAVEL = "travel",
  COMPUTER_SCIENCE = "computer-science",
  FITNESS = "fitness",
  PODCASTS = "podcasts",
  SOCIAL_MEDIA = "social-media",
  GAMING = "gaming",
  AGENCIES = "agencies",
  SPIRITUALITY = "spirituality",
  AI = "ai",
  DATING = "dating",
  BUSINESS = "business",
  MISC = "misc",
  RECREATION = "recreation",
}

export const campaignTypeLabels: Record<CampaignType, string> = {
  [CampaignType.LIVESTREAMS]: "Livestreams",
  [CampaignType.CONTENT_REWARDS]: "Content Rewards",
  [CampaignType.APP_STORE]: "App Store",
  [CampaignType.TRADING]: "Trading",
  [CampaignType.SPORTS_PICKS]: "Sports Picks",
  [CampaignType.RESELLING]: "Reselling",
  [CampaignType.ECOMMERCE]: "E-commerce",
  [CampaignType.REAL_ESTATE]: "Real Estate",
  [CampaignType.PERSONAL_DEVELOPMENT]: "Personal Development",
  [CampaignType.PERSONAL_FINANCE]: "Personal Finance",
  [CampaignType.CAREERS]: "Careers",
  [CampaignType.TRAVEL]: "Travel",
  [CampaignType.COMPUTER_SCIENCE]: "Computer Science",
  [CampaignType.FITNESS]: "Fitness",
  [CampaignType.PODCASTS]: "Podcasts",
  [CampaignType.SOCIAL_MEDIA]: "Social Media",
  [CampaignType.GAMING]: "Gaming",
  [CampaignType.AGENCIES]: "Agencies",
  [CampaignType.SPIRITUALITY]: "Spirituality",
  [CampaignType.AI]: "AI",
  [CampaignType.DATING]: "Dating",
  [CampaignType.BUSINESS]: "Business",
  [CampaignType.MISC]: "Misc",
  [CampaignType.RECREATION]: "Recreation",
};
